# Generated by Django 3.2.9 on 2021-12-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('stu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo4.stu')),
                ('dno', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
            ],
            bases=('demo4.stu',),
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo4.address')),
                ('courses', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
            bases=('demo4.address',),
        ),
    ]
