# Generated by Django 3.2.9 on 2021-12-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('aadhar', models.BigIntegerField()),
                ('salary', models.FloatField()),
                ('design', models.CharField(choices=[['account', 'ACCOUNT'], ['manager', 'MANAGER']], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('aadhar', models.BigIntegerField()),
                ('cost', models.FloatField()),
                ('course', models.CharField(choices=[['python', 'PYTHON'], ['manual', 'MANUAL'], ['datascience', 'datascience']], max_length=50)),
                ('marks', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('aadhar', models.BigIntegerField()),
                ('salary', models.FloatField()),
                ('design', models.CharField(choices=[['development', 'DEVELOPMENT'], ['testing', 'TESTING']], max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
