# Generated by Django 3.2.9 on 2021-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstration',
            name='city',
            field=models.CharField(default='hai', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminstration',
            name='country',
            field=models.CharField(default='haii', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminstration',
            name='dno',
            field=models.CharField(default='haii', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminstration',
            name='pin',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminstration',
            name='state',
            field=models.CharField(default='ABC@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminstration',
            name='street',
            field=models.CharField(default='venuf', max_length=40),
            preserve_default=False,
        ),
    ]
