# Generated by Django 3.2.9 on 2021-12-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adhaar', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='facutly',
            fields=[
                ('details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo5.details')),
                ('course', models.CharField(choices=[['Python full stack', 'PYTHON FULL STACK'], ['Python Testing', 'PYTHON TESTING'], ['Python DataScience', 'PYTHON DATASCIENCE']], max_length=100)),
                ('salary', models.FloatField()),
            ],
            bases=('demo5.details',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo5.details')),
                ('course', models.CharField(choices=[['Python', 'PYTHON'], ['Testing', 'TESTING'], ['DataScience', 'DATASCIENCE']], max_length=50)),
                ('marks', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
            bases=('demo5.details',),
        ),
    ]
