# Generated by Django 3.2.9 on 2021-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
