# Generated by Django 3.2.9 on 2021-12-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('sid1', models.IntegerField()),
                ('sid2', models.BigAutoField(primary_key=True, serialize=False)),
                ('sid3', models.BigIntegerField()),
                ('sid4', models.FloatField()),
                ('sid5', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sid6', models.DurationField()),
                ('sname3', models.BooleanField()),
                ('ip', models.GenericIPAddressField()),
                ('ip1', models.BinaryField()),
                ('date1', models.DateField()),
                ('date2', models.DateTimeField()),
                ('date3', models.TimeField()),
                ('sname', models.CharField(max_length=150)),
                ('sanme1', models.URLField(max_length=150)),
                ('sname2', models.UUIDField()),
                ('email', models.EmailField(max_length=150)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
