# Generated by Django 3.2.9 on 2021-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='jhh', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='doj',
            field=models.DateField(default='1995-06-06'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=150),
        ),
    ]
